### PR TITLE
New UI:)

### PR DESCRIPTION
**Pull request by 53gf4u1t**
Implemented!

### CODE REVIEW

**Comment by Anikesh02** [comment]
Can you attach a preview of your work?

**Comment by 53gf4u1t** [comment]
image
image
image
Here you go:) I haven't put the images in yet, will be working on that and some effects

**Comment by 53gf4u1t** [comment]
Can you specify the images to use for the features section and 3 courses to put on the top of the page?

**Comment by Anikesh02** [comment]
@nguyenhoanglienson For now you can just use any images related to our feature from google. Later we'll be changing with our images.

Is your UI responsive ?

Please resolve merge conflicts before raising PR

**Comment by 53gf4u1t** [comment]
@Anikesh02 I fixed some responsive issue, it should now looks good on large screens!

**Review by Anikesh02 — APPROVED** [review]

**Pull request merged**
